### ISSUE TITLE
KeyError: avg_order_size, which in features_config, yet not integrated into X in processor.py, but used at Line 207?

### ISSUE THREAD

**Issue by Joecth** [banditml/banditml#66]
Hi, I get KeyError while running the QuickStart steps, 
Could you please help to give a hint? 
Thanks!

Following shows the Pic regarding my problem,
![image](https://user-images.githubusercontent.com/11677095/102446839-a772e280-4069-11eb-96f5-e9b02930bc8a.png)

That is to say,
At line 207,  In processor.py, 
According to the Quick Start, the avg_order_size is from 
features_config[“features”], 
features_config = {
  "features": {
      "avg_order_size": {"type": "N"},
...

And,  I can’t see anywhere X in processor.py, which is mainly from data_frame, integrates avg_order_size into itself, 
Data_Frame:
| row | mdp_id | sequence_number | context                      | decision | reward |
|-----|--------|-----------------|------------------------------|----------|--------|
|  1  |  u123  |        1        | {"country": 2, "year": 1796} |  female  |  154.2 |
|  2  |  u456  |        1        | {"country": 4, "year": 2017} |   male   |  170.9 |

which makes me don't know how to fix it by making sense...

**Comment by econti** [comment]
Hey @Joecth - `features` should match the features present in your `context`.  See `example_feature_config.json` for an example.

**Comment by Joecth** [comment]
Thanks for your reply, @econti! 
Just now, I already simply replace features_config on QuickStart page with the content in  example_feature_config.json, shown as the pic,
<img width="595" alt="圖片" src="https://user-images.githubusercontent.com/11677095/102572115-3cd3ac80-4126-11eb-8917-dd98d5f78d6f.png">

I can see the `features` includes `country`, `year`, and `decision`, which is already consistent with `context` in DataFrame.

However, looks like it receives an empty array in preprocess_feature() in proprocessor.py, and thus raised ValueError...
<img width="1254" alt="圖片" src="https://user-images.githubusercontent.com/11677095/102572448-1f531280-4127-11eb-8fb3-bdcdddace032.png">

Is it possible for you to guide a quick fix regarding what happened here? 
(p.s. I just wanna smoothly and successfully run it up to get more idea abt it according to QuickStart.., but still not able to... )

Thanks~!
